# Generated by Django 4.1.5 on 2023-02-09 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture_url',
            field=models.ImageField(blank=True, null=True, upload_to='users/'),
        ),
    ]
