# Generated by Django 4.1.5 on 2023-02-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_liked_by_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='liked_by_user',
        ),
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='api/media/'),
        ),
    ]
