# Generated by Django 4.1.5 on 2023-02-08 00:11

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_post_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=django_quill.fields.QuillField(),
        ),
    ]
