# Generated by Django 4.1.5 on 2023-02-16 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_bookmark_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='user',
            new_name='author',
        ),
    ]
