# Generated by Django 4.1.5 on 2023-02-16 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_user_bookmark_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='author',
            new_name='user',
        ),
    ]
