# Generated by Django 4.1.5 on 2023-02-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_user_profile_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, default='No description provided...', max_length=1000, null=True),
        ),
    ]
