# Generated by Django 4.1.5 on 2023-05-07 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_notification_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='answer_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='depth',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
