# Generated by Django 4.1.5 on 2023-05-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_comment_answer_to_comment_depth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='depth',
            field=models.IntegerField(null=True),
        ),
    ]
