# Generated by Django 4.1.5 on 2023-05-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_comment_children_alter_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='outermost_parent_id',
            field=models.IntegerField(null=True),
        ),
    ]
